export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const RECEIVE_LOGIN_USER_SUCCESS = "RECEIVE_LOGIN_USER_SUCCESS";
export const RECEIVE_LOGIN_USER_ERROR = "RECEIVE_LOGIN_USER_ERROR";

export const REQUEST_LOGOUT_USER = "REQUEST_LOGOUT_USER";
export const RECEIVE_LOGOUT_USER_SUCCESS = "RECEIVE_LOGOUT_USER_SUCCESS";
export const RECEIVE_LOGOUT_USER_ERROR = "RECEIVE_LOGOUT_USER_ERROR";

export const REQUEST_TAGS = "REQUEST_TAGS";
export const RECEIVE_TAGS_SUCCESS = "RECEIVE_TAGS_SUCCESS";
export const RECEIVE_TAGS_ERROR = "RECEIVE_TAGS_ERROR";
