# Generated by Django 3.1.5 on 2023-01-03 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('flagging_reason', models.TextField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=144, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_of_action', models.DateTimeField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
            options={
                'db_table': 'flag_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TwitterVideo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('date_saved_utc', models.DateTimeField()),
                ('slug', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('parent_tweet_id', models.BigIntegerField()),
                ('video_thumbnail_link_https', models.TextField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=290, null=True)),
                ('flagged', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'twitter_videos',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('twitter_videos', models.ManyToManyField(blank=True, related_name='tags', to='scraper.TwitterVideo')),
            ],
            options={
                'db_table': 'video_tags',
                'managed': True,
            },
        ),
    ]
