# Generated by Django 3.1.5 on 2021-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittervideo',
            name='video_thumbnail_link_https',
            field=models.TextField(blank=True, null=True),
        ),
    ]
