# Generated by Django 3.1.5 on 2021-04-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittervideo',
            options={},
        ),
    ]
