# Generated by Django 3.1.5 on 2022-01-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_twittervideo_video_thumbnail_link_https'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittervideo',
            name='text',
            field=models.CharField(blank=True, max_length=290, null=True),
        ),
    ]
