# Generated by Django 3.1.5 on 2022-07-26 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_twittervideo_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('video_id', models.UUIDField()),
                ('flagging_reason', models.TextField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=144, null=True)),
                ('date_flagged', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField()),
            ],
            options={
                'db_table': 'flag_requests',
            },
        ),
    ]
