# Generated by Django 3.1.5 on 2022-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_add_table_for_tracking_flag_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagrequest',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
