# Generated by Django 3.1.5 on 2022-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_edit_date_approved_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagrequest',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
