# Generated by Django 3.1.5 on 2022-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_remove_unique_constraint_from_slug_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flagrequest',
            old_name='date_approved',
            new_name='date_of_action',
        ),
        migrations.AddField(
            model_name='flagrequest',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
