# Generated by Django 3.1.5 on 2022-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_add_request_status_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flagrequest',
            old_name='date_flagged',
            new_name='date_requested',
        ),
    ]
