# Generated by Django 3.1.5 on 2022-07-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20220728_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flagrequest',
            name='is_approved',
        ),
    ]
