export const GET_FLAG_REQUEST = 'GET_FLAG_REQUEST';
export const GET_FLAG_REQUEST_SUCCESS = 'GET_FLAG_REQUEST_SUCCESS';
export const GET_FLAG_REQUEST_ERROR = 'GET_FLAG_REQUEST_ERROR';

export const POST_FLAG_REQUEST = 'POST_FLAG_REQUEST';
export const POST_FLAG_REQUEST_SUCCESS = 'POST_FLAG_REQUEST_SUCCESS';
export const POST_FLAG_REQUEST_ERROR = 'POST_FLAG_REQUEST_ERROR';

export const GET_SLUG_FLAG_REQUESTS = 'GET_SLUG_FLAG_REQUESTS';
export const GET_SLUG_FLAG_REQUESTS_SUCCESS = 'GET_SLUG_FLAG_REQUESTS_SUCCESS';
export const GET_SLUG_FLAG_REQUESTS_ERROR = 'GET_SLUG_FLAG_REQUESTS_ERROR';

export const SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS =
	'SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS';
export const SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS_SUCCESS =
	'SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS_SUCCESS';
export const SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS_ERROR =
	'SUBMIT_FLAG_REQUESTS_APPROVAL_STATUS_ERROR';

export const GET_VIDEO = 'GET_VIDEO';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_ERROR = 'GET_VIDEO_ERROR';

export const FLAG_VIDEO = 'FLAG_VIDEO';
export const FLAG_VIDEO_SUCCESS = 'FLAG_VIDEO_SUCCESS';
export const FLAG_VIDEO_ERROR = 'FLAG_VIDEO_ERROR';
