export const GET_FLAG_REQUEST = 'GET_FLAG_REQUEST';
export const GET_FLAG_REQUEST_SUCCESS = 'GET_FLAG_REQUEST_SUCCESS';
export const GET_FLAG_REQUEST_ERROR = 'GET_FLAG_REQUEST_ERROR';

export const POST_FLAG_REQUEST = 'POST_FLAG_REQUEST';
export const POST_FLAG_REQUEST_SUCCESS = 'POST_FLAG_REQUEST_SUCCESS';
export const POST_FLAG_REQUEST_ERROR = 'POST_FLAG_REQUEST_ERROR';
